spring:
  cloud:
    stream:
      bindings:
        output:
          destination: myDestination
          binder: localBinder
        input:
          destination: myDestination
          binder: localBinder
          group: consumerGroup    # 消息组，当需要重发的时候，必输
          consumer:
            max-attempts: 1     # 消息不会自动重发
      binders:
        localBinder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.86.24
                port: 5672
                username: test
                password: test@123
                virtual-host: /
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true        # 自动启用DLQ
              dlqTtl: 3000             # DLQ停3秒再走
              dlqDeadLetterExchange:    # 关联DLX
